[package]
name = "passenger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.17.8"
rand = "0.8.5"
aes-gcm = "0.10.3"
log = "0.4.21"
anyhow = "1.0.81"
rpassword = "7.3.1"